version: '3.8'
services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: 1111
      POSTGRES_DB: telegramservicedb
    ports:
      - "5432:5432"

  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest

  telegram-service:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__Postgres=Host=db;Database=telegramservicedb;Username=user;Password=1111
      - RabbitMQ__HostName=rabbitmq
      - RabbitMQ__UserName=user
      - RabbitMQ__Password=password
      - ConnectionStrings__RabbitMQ=amqp://guest:guest@rabbitmq:5672
    depends_on:
      - db
      - rabbitmq
    ports:
      - "5010:80"